site_name: Off-the-Grid MARL
site_author: InstaDeep Research
site_url: https://instadeepai.github.io/_draft/og-marl/
site_dir: public

theme:
  name: material
  logo: assets/instadeep_logo.png
  favicon: assets/instadeep_logo.png
  language: en
  features:
    - navigation.tracking # the URL is automatically updated with the active anchor
    - navigation.sections # top-level sections are rendered as groups in the sidebar
    - navigation.tabs # horizontal tabs at the top of the page
    - navigation.tabs.sticky # navigation tabs will lock below the header and always remain visible when scrolling
    - navigation.indexes # documents can be directly attached to sections
    - search.highlight # highlight search result
    - search.share # share button
    - search.suggest # smart suggestion
    # - toc.integrate
    - toc.follow
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.tabs
    - navigation.top
  palette:
    - scheme: default
      primary: white
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to light mode

nav:
  - Home: 'index.md'
  - Baseline Results: 'baselines.md'
  - Updates: 'updates.md'
  - API Reference:
      - Systems: 'api/systems.md'
      - Environments: 'api/envs.md'
      - Types: 'api/types.md'
      - Datasets: 'api/datasets.md'

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      emoji_index: !!python/name:pymdownx.emoji.gemoji
  - pymdownx.snippets:
      base_path: ./
  - pymdownx.pathconverter:
      base_path: ./
      relative_path: docs
  - toc:
      permalink: "🔌"
      toc_depth: 4
  - pymdownx.highlight:
      linenums: true
  - def_list
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink


# Git repo
repo_name: instadeepai/og-marl
repo_url: https://github.com/instadeepai/og-marl
edit_uri: edit/develop/docs/

# Copyright
copyright: InstaDeep © 2022 Copyright, all rights reserved.

# Plugins
plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          import:
          - https://docs.python.org/3/objects.inv
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: false
            merge_init_into_class: false
            show_root_heading: true
            show_source: false
            show_if_no_docstring: false
            # show_signature: true
            # show_signature_annotations: false
            show_root_full_path: false
            docstring_section_style: spacy
            members_order: source
            heading_level: 3
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_signature: false
            # separate_signature: true
            signature_crossrefs: true
            summary: true
          selection:
            inherited_members: true
